// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ResetToolWindows
{
    internal sealed partial class Vsix
    {
        public const string Id = "MadsKristensen.ResetToolWindow";
        public const string Name = "Reset Tool Windows";
        public const string Description = @"Collapse all tool windows except the ones you really need visible and gain 10-33% faster Visual Studio startup times and a fresh starting point every day.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "tool window, cleanup, solution explorer";
    }
}
